### PR TITLE
Fix two misspelled words

### PR DESCRIPTION
**Pull request by kwilczynski**
### What changes were proposed in this pull request?

Spelling of words _specific_ and _shape_ has been corrected.

### Why are the changes needed?

To resolve spelling errors and improve correctness of the user-facing documentation.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @kwilczynski,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by kwilczynski** [comment]
[...]
> Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:
> 
> http://www.lightbend.com/contribute/cla

CLA has been signed.

**Comment by kwilczynski** [comment]
This is a trivial change that fixes misspelling of two words I've found while reading the documentation available on-line at https://cloudflow.io/docs/current/index.html.

**Comment by agemooij** [comment]
Thanks @kwilczynski !

**Pull request merged**
